SELECT 'S1/S2 A/W - Samples', (SELECT COUNT(*) FROM Samples)
FROM dual
UNION
SELECT 'S1 B - Lab Technicians', (SELECT COUNT(*) FROM Lab_Technicians)
FROM dual
UNION
SELECT 'S1/S2 D/Z - Measurements', (SELECT COUNT(*) FROM Measurements)
FROM dual
UNION
SELECT 'S1 C - Instruments', (SELECT COUNT(*) FROM Instruments)
FROM dual
UNION
SELECT 'S1/S2 /W- Laboratories' AS table_name, (SELECT COUNT(*) FROM Laboratories) AS table_count
FROM dual
UNION
/*SELECT 'S2 W - Laboratories' AS table_name, (SELECT COUNT(*) FROM Laboratories) AS table_count
FROM dual
UNION
SELECT 'S2 X - Measurements', (SELECT COUNT(*) FROM MEASUREMENTS)
FROM dual
UNION*/
SELECT 'S2 Y - Reports', (SELECT COUNT(*) FROM REPORTS)
FROM dual
UNION
SELECT 'S2 X - Campaigns', (SELECT COUNT(*) FROM CAMPAIGNS)
FROM dual
UNION
SELECT 'S2 - Contacs', (SELECT COUNT(*) FROM CONTACTS)
FROM dual;

ALTER PACKAGE PKG_SAMENS1_M4_LABORATORIES COMPILE BODY;
ALTER PACKAGE PKG_SAMENS2_M4_LABORATORIES COMPILE BODY;

BEGIN
    PKG_SAMENS1_M4_LABORATORIES.EMPTY_TABLES_S1();
END;
BEGIN
    PKG_SAMENS1_M4_LABORATORIES.BEWIJS_MILESTONE_M4_S1();
end;
BEGIN
    PKG_SAMENS2_M4_LABORATORIES.EMPTY_TABLES_S2();
END;
BEGIN
    PKG_SAMENS2_M4_LABORATORIES.BEWIJS_MILESTONE_M4_S2();
end;
commit;
