SELECT 'S2 W - Laboratories' AS table_name, (SELECT COUNT(*) FROM Laboratories) AS table_count
FROM dual
UNION
SELECT 'S2 Z - Measurements', (SELECT COUNT(*) FROM MEASUREMENTS)
FROM dual
UNION
SELECT 'S2 Y - Reports', (SELECT COUNT(*) FROM REPORTS)
FROM dual
UNION
SELECT 'S2 X - Campaigns', (SELECT COUNT(*) FROM CAMPAIGNS)
FROM dual
UNION
SELECT 'S2 - Contacs', (SELECT COUNT(*) FROM CONTACTS)
FROM dual;

ALTER PACKAGE PKG_S2_LABORATORIES COMPILE BODY;
ALTER PACKAGE PKG_S1_LABORATORIES COMPILE BODY;

BEGIN
    PKG_S1_LABORATORIES.EMPTY_TABLES_S1();
end;
BEGIN
    PKG_S1_LABORATORIES.BEWIJS_MILESTONE_M4_S1();
end;
BEGIN
    PKG_S2_LABORATORIES.EMPTY_TABLES_S2();
END;
BEGIN
    PKG_S2_LABORATORIES.BEWIJS_MILESTONE_M4_S2();
END;
BEGIN
    PKG_S2_LABORATORIES.BEWIJS_MILESTONE_M7_S2(30,30,30,600,false);
end;
commit;




